---
section: deploy
title: Implementieren Sie ONTAP-Tools f체r VMware vSphere
entries:
- title: Voraussetzungen
  url: "/deploy/sizing-requirements.html"
- title: Konfigurationseinschr채nkungen
  url: "/deploy/config-limits.html"
- title: Bereiten Sie die Implementierung von ONTAP Tools vor
  url: "/deploy/prepare-deployment.html"
- title: ONTAP Tools herunterladen
  url: "/deploy/download-ontap-tools.html"
- title: Implementierung einer Single Node-Konfiguration ohne Hochverf체gbarkeit
  url: "/deploy/nonha-deployment.html"
- title: Implementierung der HA-Konfiguration
  url: "/deploy/ha-three-node-deployment.html"
- title: Recovery
  url: "/deploy/recovery-deployment.html"
- title: Fehlercodes f체r die Bereitstellung
  url: "/deploy/deployment-error-codes.html"
