---
section: deploy
title: Implementieren Sie ONTAP-Tools f端r VMware vSphere
entries:
- title: Voraussetzungen
  url: "/deploy/sizing-requirements.html"
- title: ONTAP Tools herunterladen
  url: "/deploy/download-ontap-tools.html"
- title: Bereiten Sie die Implementierung von ONTAP Tools vor
  url: "/deploy/prepare-deployment.html"
- title: Implementierung einer Single Node-Konfiguration ohne Hochverf端gbarkeit
  url: "/deploy/nonha-deployment.html"
- title: Implementierung der HA-Konfiguration
  url: "/deploy/ha-three-node-deployment.html"
- title: Stellen Sie Ihre ONTAP Tools f端r die Einrichtung von VMware vSphere wieder
    her
  url: "/deploy/recovery-deployment.html"
- title: Fehlercodes f端r die Bereitstellung
  url: "/deploy/deployment-error-codes.html"
